apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: react-app-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app-container
          image: enachedaniel19/react-app:latest
          ports:
            - containerPort: 3000